name: Push and Deploy

on:
  workflow_dispatch
  
env:
  IMAGE_NAME: mkfl3x/welcome-tg-bot
  CONTAINER_NAME: welcome-tg-bot

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v3
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
          
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/welcome-tg-bot:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}
            docker image rm ${{ env.IMAGE_NAME }}
            docker run -d -e BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }} --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}
